# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Mana',
            fields=[
                ('mana_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Mana')),
                ('bond', models.CharField(choices=[('tapped', 'Tapped'), ('bound', 'Bound')], max_length=10)),
            ],
            bases=('game.mana',),
        ),
        migrations.CreateModel(
            name='Realm_Mana',
            fields=[
                ('mana_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Mana')),
                ('position', models.SmallIntegerField()),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Realm')),
            ],
            bases=('game.mana',),
        ),
        migrations.AddField(
            model_name='mana',
            name='origin_realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Realm'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Realm'),
        ),
        migrations.AddField(
            model_name='character_mana',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character'),
        ),
    ]
