# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Blarg', max_length=30),
            preserve_default=False,
        ),
    ]
